package tadp.parsers

class StringVacioException extends Exception
class CharException extends Exception
class IsDigitException extends Exception
class StringException extends Exception
class ConcatException extends Exception
class MapException extends Exception
class SatisfiesException extends Exception
class FiguraInvalidaException extends Exception
class ColorInvalidoException extends Exception